/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Form: typeof import('@remix-run/react')['Form']
  const Link: typeof import('@remix-run/react')['Link']
  const Links: typeof import('@remix-run/react')['Links']
  const Meta: typeof import('@remix-run/react')['Meta']
  const NavLink: typeof import('@remix-run/react')['NavLink']
  const Outlet: typeof import('@remix-run/react')['Outlet']
  const Scripts: typeof import('@remix-run/react')['Scripts']
  const ScrollRestoration: typeof import('@remix-run/react')['ScrollRestoration']
  const createCookieSessionStorage: typeof import('@remix-run/node')['createCookieSessionStorage']
  const createRef: typeof import('react')['createRef']
  const forwardRef: typeof import('react')['forwardRef']
  const i18n: typeof import('./app/utils/.server/i18n')['default']
  const i18nServerInitOptions: typeof import('./app/utils/.server/i18n')['i18nServerInitOptions']
  const isRouteErrorResponse: typeof import('@remix-run/react')['isRouteErrorResponse']
  const json: typeof import('@remix-run/node')['json']
  const lazy: typeof import('react')['lazy']
  const memo: typeof import('react')['memo']
  const redirect: typeof import('@remix-run/node')['redirect']
  const startTransition: typeof import('react')['startTransition']
  const useActionData: typeof import('@remix-run/react')['useActionData']
  const useCallback: typeof import('react')['useCallback']
  const useContext: typeof import('react')['useContext']
  const useDebugValue: typeof import('react')['useDebugValue']
  const useDeferredValue: typeof import('react')['useDeferredValue']
  const useEffect: typeof import('react')['useEffect']
  const useFetcher: typeof import('@remix-run/react')['useFetcher']
  const useId: typeof import('react')['useId']
  const useImperativeHandle: typeof import('react')['useImperativeHandle']
  const useInsertionEffect: typeof import('react')['useInsertionEffect']
  const useLayoutEffect: typeof import('react')['useLayoutEffect']
  const useLoaderData: typeof import('@remix-run/react')['useLoaderData']
  const useMemo: typeof import('react')['useMemo']
  const useNavigation: typeof import('@remix-run/react')['useNavigation']
  const useParams: typeof import('@remix-run/react')['useParams']
  const useReducer: typeof import('react')['useReducer']
  const useRef: typeof import('react')['useRef']
  const useRouteError: typeof import('@remix-run/react')['useRouteError']
  const useSearchParams: typeof import('@remix-run/react')['useSearchParams']
  const useState: typeof import('react')['useState']
  const useSubmit: typeof import('@remix-run/react')['useSubmit']
  const useSyncExternalStore: typeof import('react')['useSyncExternalStore']
  const useTransition: typeof import('react')['useTransition']
  const useTranslation: typeof import('react-i18next')['useTranslation']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { LinksFunction, LoaderFunctionArgs, ActionFunctionArgs, MetaFunction } from '@remix-run/node'
  import('@remix-run/node')
}
