x-common: &common
  network_mode: service:app

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  db:
    <<: [*common]
    image: postgres:alpine
    environment:
      # - POSTGRES_DB=postgres
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ../data/db:/var/lib/postgresql/data

  # redis:
  #   <<: [*common]
  #   image: redis:alpine
  #   volumes:
  #     - ../data/redis:/data

  admin:
    image: dpage/pgadmin4
    container_name: admin
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=uwu@nafnix.com
      - PGADMIN_DEFAULT_PASSWORD=uwu@nafnix.com
    ports:
      - 8000:80
    volumes:
      - admin-data:/var/lib/pgadmin

volumes:
  admin-data:
