x-common: &common
  network_mode: service:app

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  db:
    <<: [*common]
    image: postgres:alpine
    environment:
      # - POSTGRES_DB=postgres
      # - POSTGRES_USER=postgres
      # - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ../data/db:/var/lib/postgresql/data

  # redis:
  #   <<: [*common]
  #   image: redis:alpine
  #   volumes:
  #     - ../data/redis:/data
